[package]
name = "cluster"
version = "0.2.0"
authors = ["Nathan Corbyn <me@nathancorbyn.com>"]
edition = "2018"

[dependencies]
toml = "0.5.1"
serde = { version = "1.0.94", features = ["derive"] }
lazy_static = "1.3.0"
